// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzectfcnxlpbdojvnske.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6ZWN0ZmNueGxwYmRvanZuc2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDMxMzMsImV4cCI6MjA3MTY3OTEzM30.piysb8WMHC1lvswErL-iyaW6h6ViURsM3Q7Q0n4_lTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});